#Site settings
name: KidsKare Academy Learning Center
description: > # this means to ignore newlines until "baseurl:"
  This is the official website for KidsKareAcademy. You can find anything
  about the academy, including registration, fees, cources, policies, etc.
baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://kidskareacademy.com" # the base hostname & protocol for your site
copyright: (C)Copyright KidsKare Academy Learning Center, 2012 - 2015

email: gaofujie@hotmail.com
phone: 425-273-6467
address: 8135 NE 147th ST, Kenmore, WA 98028
servearea: Serving Northshore, Lake Washington School Districts(Kenmore, Bothell, Kirkland, etc) since 2012
servicecolor: color:green

standardname: KidsKareAcademy
twitter_username: Kids_Kare
github_username:  kidskareacademy
facebook_username:  kidskareacademy


#Home page settings:
welcome-color: color:red
welcome: Welcome to 

generaltextcolor: color:black
scheduletextcolor: color:red
scheduletitlecolor: color:green

homevideo_desc: Watch the above video to see what the students achieved after 100 days

licensed: State licensed before and after school learning center
specific1: Experienced Chinese and Math teacher in NWCS(Northwest Chinese School)
specific2: 45 minutes guaranteed academic learning everyday, including Singapore Math and Chinese reading & writing
specific3: School homework individual tutoring
specific4: Small-sized class(maximum - 8)
specific5: Spacious and clean new house, around 2000sf open to kids
specific6: Offer transportation from school and one snack

transportation: >
  Van transportation is provided to and from Moorlands, Kenmore, Thoreau, Arrowhead, Juanita, Carl Sandberg, 
  Shelton View and SunRise.

snacks: >
  For after school students, we serve a nutritious free snack.
  Food brought from home are stored in the refrigerator in the break room.

schedule: KidsKareAcademy is open Monday through Friday. The academic learning schedule is as follows,

closeinfo: 

#Wizard tab settings:
wizard1URL: /
wizard1title: Home page
wizard1Display: Home

wizard2URL: /AfterSchool
wizard2title: After school program and rate
wizard2Display: After School

wizard3URL: /BeforeSchool
wizard3title: Before school program and rate
wizard3Display: Before School

wizard4URL: /WeekendChinese
wizard4title: Weekend Chinese Program and rate
wizard4Display: Weekend Chinese

wizard5URL: /DropIn
wizard5title: Drop in Program and rate
wizard5Display: Drop in

wizard6URL: /AdmissionForms
wizard6title: The forms you need fill
wizard6Display: Forms
   
wizard7URL: /videos.html
wizard7title: Interesting videos
wizard7Display: Videos

wizard8URL: /pictures.html
wizard8title: Interesting pictures
wizard8Display: Pictures

wizard9URL: /contact.html
wizard9title: All contact info here
wizard9Display: Contact us   

wizard10URL: /documents.html
wizard10title: you can find all info you want to know here 
wizard10Display: Documents

wizard11URL: 
wizard11Display: 

wizard12URL: 
wizard12Display: 

wizard13URL: 
wizard13Display:

wizard14URL: 
wizard14Display:

homevideo: /videos/100days.mp4

schedule-period:  Monday - Friday:
schedule-1-class: Chinese:
schedule-1-type:  Reading & Writing
schedule-1-period: 40 mins

schedule-2-class: Singapore Math:
schedule-2-type: Supervise & answer questions      
schedule-2-period: 40 mins

schedule-type2:    Singapore Math
schedule-type2-period:  45 mins

schedule-wed:  Wed
schedule-wed-type:     Chinese
schedule-wed-period:   45 mins

schedule-thur: Thu
schedule-thur-type:    Singapore Math
schedule-thur-period:  40 mins

schedule-fri:  Fri
schedule-fri-type:     Chinese
schedule-fri-period:   45 mins

#Picture settings:
picture1: /pictures/1.jpg
picture2: /pictures/2.jpg
picture3: /pictures/3.jpg
picture4: /pictures/4.jpg
picture5: /pictures/5.jpg
picture6: /pictures/6.jpg
picture7: /pictures/7.jpg
picture8: /pictures/8.jpg
picture9: /pictures/9.jpg
picture10: /pictures/10.jpg
picture11: /pictures/11.jpg
picture12: /pictures/12.jpg
picture13: /pictures/13.jpg
picture14: /pictures/14.jpg
picture15: /pictures/15.jpg
picture16: /pictures/16.jpg
picture17: /pictures/17.jpg
picture18: /pictures/18.jpg
picture19: /pictures/19.jpg
picture20: /pictures/20.jpg
picture21: /pictures/21.jpg
picture22: /pictures/22.jpg
picture23: /pictures/23.jpg
picture24: /pictures/24.jpg
picture25: /pictures/25.jpg
picture26: /pictures/26.jpg
picture27: /pictures/27.jpg
picture28: /pictures/28.jpg
picture29: /pictures/29.jpg
picture30: /pictures/30.jpg
picture31: /pictures/31.jpg
picture32: /pictures/32.jpg
picture33: /pictures/33.jpg
picture34: /pictures/34.jpg
picture35: /pictures/35.jpg
picture36: /pictures/36.jpg



picture1_desc: Doing reading project
picture2_desc: Field trip to Bothell library
picture3_desc: Dino Art
picture4_desc: Outside playing time
picture5_desc: Bicycling in the cul-de-sac
picture6_desc: Birthday Party
picture7_desc: Chess Corner
picture8_desc: Reading Corner
picture9_desc: Quiet safe cul-de-sac
picture10_desc: Field Trip to Pacific Science Center
picture11_desc: Field Trip to Pacific Science Center
picture12_desc: Home Picture
picture13_desc: Home Picture
picture14_desc: Field Trip to Pacific Science Center
picture15_desc: Field Trip to Downtown Seattle
picture16_desc: Field Trip to Juanita Beach Park
picture17_desc: Playing in the backyard
picture18_desc: Play Room
picture19_desc: Bead Art Project
picture20_desc: Field Trip to Pacific Science Center
picture21_desc: Kitchen
picture22_desc: Class Place
picture23_desc: Puzzle Time
picture24_desc: Biscuit and Angel
picture25_desc: Biscuit and Angel
picture26_desc: Extra Class Table
picture27_desc: Office for Art Project
picture28_desc: Quiet Reading Corner
picture29_desc: Birthday Party
picture30_desc: Halloween Party
picture31_desc: Halloween Party
picture32_desc: Student Chinese Writing Work - The snake from heaven, Page 1
picture33_desc: Student Chinese Writing Work - The snake from heaven, Page 2
picture34_desc: Student Chinese Writing Work - The snake from heaven, Page 3
picture35_desc: Student Chinese Writing Work - The snake from heaven, Page 4
picture36_desc: Student Chinese Writing Work - The snake from heaven, Page 5


#Video settings:
video1: /videos/100days.mp4
video1_desc: The students achieved after 100 days 
video2: /videos/2.mp4
video2_desc: Goodbye party to Kathrine 

#Document settings
policycolor: color:red


#Contact settings:
LatLng: 47.7348519, -122.231203

# Build settings
markdown: kramdown

